# Configuration of generators (defaults illustrated)
---
# The directory where the generated files are stored
# directory: "tmp"

# By default all generators are run. Specify here the ones to skip.
excludes:
  - markdown

# Alternatively only specify the generators to run
# (comment out the above "excludes" section)
# includes:
#   - markdown
#   - excel

# Set the arguments for the generators (no matter if they run or not)
generator_args:
  excel:
    mergeimports: true
  owl:
    mergeimports: true
    metaclasses: true
    type_objects: true
    # throws 'Cannot handle metadata profile: rdfs'
    # metadata_profile: rdfs
  markdown:
    mergeimports: true
    directory: "docs/elements"
  graphql:
    mergeimports: true
  # gen-java is not yet supported by gen-project.
  #   https://github.com/linkml/linkml/issues/2537
  # java:
  #   mergeimports: true
  #   metadata: true
  jsonld:
    mergeimports: true
  jsonschema:
    mergeimports: true
  jsonldcontext:
    mergeimports: true
  # gen-pydantic is not yet supported by gen-project.
  #   https://github.com/linkml/linkml/issues/2537
  # pydantic:
  #   mergeimports: true
  python:
    mergeimports: true
    # head: true  # Why does this not work?
  prefixmap:
    mergeimports: true
  proto:
    mergeimports: true
  shacl:
    mergeimports: true
  shex:
    mergeimports: true
  sqlddl:
    mergeimports: true
  typescript:
    mergeimports: true
    metadata: true

...
